# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: npm install && ELEVENTY_EXPERIMENTAL=true  DEBUG=Eleventy* npx @11ty/eleventy

      - name: Deploy to Production Branch 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: production # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
